/**
 * This file was generated by the JPA Modeler
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author albert
 */
@Entity
public class Animale {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String nome;

    @Basic
    private String numeroFemmine;

    @Basic
    private String numeroMaschi;

    @Basic
    private String nCuccioliFemmine;

    @Basic
    private String nCuccioliMaschi;

    @Basic
    private String livelloSalute;

    @Basic
    private String rischioEstinzione;

    @Basic
    private String annoPrimoAvvistamento;

    @ManyToOne(targetEntity = Parco.class)
    private Parco parco;

    @ManyToOne(targetEntity = Specie.class)
    private Specie specie;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getNumeroFemmine() {
        return this.numeroFemmine;
    }

    public void setNumeroFemmine(String numeroFemmine) {
        this.numeroFemmine = numeroFemmine;
    }

    public String getNumeroMaschi() {
        return this.numeroMaschi;
    }

    public void setNumeroMaschi(String numeroMaschi) {
        this.numeroMaschi = numeroMaschi;
    }

    public String getNCuccioliFemmine() {
        return this.nCuccioliFemmine;
    }

    public void setNCuccioliFemmine(String nCuccioliFemmine) {
        this.nCuccioliFemmine = nCuccioliFemmine;
    }

    public String getNCuccioliMaschi() {
        return this.nCuccioliMaschi;
    }

    public void setNCuccioliMaschi(String nCuccioliMaschi) {
        this.nCuccioliMaschi = nCuccioliMaschi;
    }

    public String getLivelloSalute() {
        return this.livelloSalute;
    }

    public void setLivelloSalute(String livelloSalute) {
        this.livelloSalute = livelloSalute;
    }

    public String getRischioEstinzione() {
        return this.rischioEstinzione;
    }

    public void setRischioEstinzione(String rischioEstinzione) {
        this.rischioEstinzione = rischioEstinzione;
    }

    public String getAnnoPrimoAvvistamento() {
        return this.annoPrimoAvvistamento;
    }

    public void setAnnoPrimoAvvistamento(String annoPrimoAvvistamento) {
        this.annoPrimoAvvistamento = annoPrimoAvvistamento;
    }

    public Parco getParco() {
        return this.parco;
    }

    public void setParco(Parco parco) {
        this.parco = parco;
    }

    public Specie getSpecie() {
        return this.specie;
    }

    public void setSpecie(Specie specie) {
        this.specie = specie;
    }

}