/**
 * This file was generated by the JPA Modeler
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * @author albert
 */
@Entity
public class Animale {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String nome;

    @Basic
    private int numeroFemmine;

    @Basic
    private int numeroMaschi;

    @Basic
    private int nCuccioliFemmine;

    @Basic
    private int nCuccioliMaschi;

    @Basic
    private int livelloSalute;

    @Basic
    private int rischioEstinzione;

    @Basic
    private String annoPrimoAvvistamento;

    @ManyToOne(targetEntity = Parco.class)
    @JoinColumn(name = "PARCO_ID")
    private Parco parco;

    @ManyToOne(targetEntity = Specie.class)
    @JoinColumn(name = "SPECIE_ID")
    private Specie specie;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public int getNumeroFemmine() {
        return this.numeroFemmine;
    }

    public void setNumeroFemmine(int numeroFemmine) {
        this.numeroFemmine = numeroFemmine;
    }

    public int getNumeroMaschi() {
        return this.numeroMaschi;
    }

    public void setNumeroMaschi(int numeroMaschi) {
        this.numeroMaschi = numeroMaschi;
    }

    public int getNCuccioliFemmine() {
        return this.nCuccioliFemmine;
    }

    public void setNCuccioliFemmine(int nCuccioliFemmine) {
        this.nCuccioliFemmine = nCuccioliFemmine;
    }

    public int getNCuccioliMaschi() {
        return this.nCuccioliMaschi;
    }

    public void setNCuccioliMaschi(int nCuccioliMaschi) {
        this.nCuccioliMaschi = nCuccioliMaschi;
    }

    public int getLivelloSalute() {
        return this.livelloSalute;
    }

    public void setLivelloSalute(int livelloSalute) {
        this.livelloSalute = livelloSalute;
    }

    public int getRischioEstinzione() {
        return this.rischioEstinzione;
    }

    public void setRischioEstinzione(int rischioEstinzione) {
        this.rischioEstinzione = rischioEstinzione;
    }

    public String getAnnoPrimoAvvistamento() {
        return this.annoPrimoAvvistamento;
    }

    public void setAnnoPrimoAvvistamento(String annoPrimoAvvistamento) {
        this.annoPrimoAvvistamento = annoPrimoAvvistamento;
    }

    public Parco getParco() {
        return this.parco;
    }

    public void setParco(Parco parco) {
        this.parco = parco;
    }

    public Specie getSpecie() {
        return this.specie;
    }

    public void setSpecie(Specie specie) {
        this.specie = specie;
    }

}