/**
 * This file was generated by the JPA Modeler
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author albert
 */
@Entity
public class Specie {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String nomeSpecie;

    @ManyToOne(targetEntity = OrdineAppartenenza.class)
    private OrdineAppartenenza ordineAppartenenza;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomeSpecie() {
        return this.nomeSpecie;
    }

    public void setNomeSpecie(String nomeSpecie) {
        this.nomeSpecie = nomeSpecie;
    }

    public OrdineAppartenenza getOrdineAppartenenza() {
        return this.ordineAppartenenza;
    }

    public void setOrdineAppartenenza(OrdineAppartenenza ordineAppartenenza) {
        this.ordineAppartenenza = ordineAppartenenza;
    }

}