/**
 * This file was generated by the JPA Modeler
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author albert
 */
@Entity
public class Vegetale {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String nomePianta;

    @Basic
    private String stagioneFioritura;

    @Basic
    private String noteVarie;

    @ManyToOne(targetEntity = Parco.class)
    private Parco parco;

    @ManyToOne(targetEntity = Tipologia.class)
    private Tipologia tipologia;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomePianta() {
        return this.nomePianta;
    }

    public void setNomePianta(String nomePianta) {
        this.nomePianta = nomePianta;
    }

    public String getStagioneFioritura() {
        return this.stagioneFioritura;
    }

    public void setStagioneFioritura(String stagioneFioritura) {
        this.stagioneFioritura = stagioneFioritura;
    }

    public String getNoteVarie() {
        return this.noteVarie;
    }

    public void setNoteVarie(String noteVarie) {
        this.noteVarie = noteVarie;
    }

    public Parco getParco() {
        return this.parco;
    }

    public void setParco(Parco parco) {
        this.parco = parco;
    }

    public Tipologia getTipologia() {
        return this.tipologia;
    }

    public void setTipologia(Tipologia tipologia) {
        this.tipologia = tipologia;
    }

}